// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2qP4R_NIPFTK6bJMQVyaNfGV4IYsuc-M',
    appId: '1:522744268708:web:a706dce2f8aa1d7631a331',
    messagingSenderId: '522744268708',
    projectId: 'ipd-210',
    authDomain: 'ipd-210.firebaseapp.com',
    storageBucket: 'ipd-210.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN868aCbuiQVu6KRGOvj0EwW1Njh8t_OQ',
    appId: '1:522744268708:android:eccad8d429b4852e31a331',
    messagingSenderId: '522744268708',
    projectId: 'ipd-210',
    storageBucket: 'ipd-210.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUchLAFfGn8nDDKU4uhtUyhB6Opq99IXA',
    appId: '1:522744268708:ios:f6c8a21b9938db9131a331',
    messagingSenderId: '522744268708',
    projectId: 'ipd-210',
    storageBucket: 'ipd-210.firebasestorage.app',
    iosBundleId: 'com.example.eventsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUchLAFfGn8nDDKU4uhtUyhB6Opq99IXA',
    appId: '1:522744268708:ios:f6c8a21b9938db9131a331',
    messagingSenderId: '522744268708',
    projectId: 'ipd-210',
    storageBucket: 'ipd-210.firebasestorage.app',
    iosBundleId: 'com.example.eventsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2qP4R_NIPFTK6bJMQVyaNfGV4IYsuc-M',
    appId: '1:522744268708:web:410271f08da7db5f31a331',
    messagingSenderId: '522744268708',
    projectId: 'ipd-210',
    authDomain: 'ipd-210.firebaseapp.com',
    storageBucket: 'ipd-210.firebasestorage.app',
  );
}
